- env: &anchor
    ANCHOR: "this is my anchor"


name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
      <<: *anchor
    - name: push content

      run: |
        echo ${{ env.ANCHOR }}

